import React from 'react';
import { Table } from 'react-bootstrap';
import '../css/Table_CSS.css';

export const Member_Screen = () => (
    <React.Fragment>
        <h2 className="header">Daftar Member Screen</h2>
        <Table className="istable" responsive striped hover variant="light">
            <thead className="head">
                <tr>
                    <th>No</th>
                    <th>Member Type Name</th>
                    <th>Member No</th>
                    <th>Member Name</th>
                    <th>Member Nickname</th>
                    <th>Place of Birth</th>
                    <th>Birth Date</th>
                    <th>Gender</th>
                    <th>Religion</th>
                    <th>Language</th>
                </tr>
            </thead>
            <tbody className="body">
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
                <tr>
                    <th>1</th>
                    <th>XXXX</th>
                    <th>XX</th>
                    <th>XXXXXXXXXXXX</th>
                    <th>XXX</th>
                    <th>XXXXX</th>
                    <th>XX/XX/XXXX</th>
                    <th>X</th>
                    <th>XXXXX</th>
                    <th>XXXXX</th>
                </tr>
            </tbody>
        </Table>
    </React.Fragment>
)